In [4]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=1bd7046baecf0bcf0f3274198e7f8b708606acc7b537eaa725efe84c1c3923b6
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Import dataset**

In [8]:
import pandas as pd

#  Added encoding='latin-1' to bypass the UTF-8 decode error
df = pd.read_csv('/content/netflix_dataset.csv', header=None, encoding='latin-1')

transaction = []
for i in range(0, 7466):
    transaction.append([str(df.values[i, j]) for j in range(0, 20)])

**Eclat Training on dataset**

In [9]:
import apyori
rules = apyori.apriori(transaction, min_support=0.003, min_confidence=0.2, min_lift=3, min_length=2, max_length=2)

**Visulizing**

In [10]:
result = list(rules)
result

[RelationRecord(items=frozenset({'Black Panther', 'Captain America'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Captain America'}), items_add=frozenset({'Black Panther'}), confidence=0.24509803921568626, lift=5.140174047146949)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'Game of thrones'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.20512820512820512, lift=3.1001764766946955)]),
 RelationRecord(items=frozenset({'Kanan Gill Comedy', 'Comedy nights with Kapil'}), support=0.008036431824270024, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Kanan Gill Comedy'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2714932126696833, lift=4.103174748566509)]),
 RelationRecord(items=frozenset({'Game of thrones', 'Prision Break'}), support=0.004553978033753014, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Prision Break'}), confidence=0.2905982905982906, lift=4.832086498010774)]),
 RelationRecord(items=frozenset({'Harry Potter 1', 'Harry Potter 2'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.36752136752136755, lift=4.642833383950135)]),
 RelationRecord(items=frozenset({'The Lord of the rings', 'Harry Potter 1'}), support=0.005089740155371015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.3247863247863248, lift=4.523982650848323)]),
 RelationRecord(items=frozenset({'crimes of grindelwald', 'Harry Potter 2'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'crimes of grindelwald'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.3006993006993007, lift=3.7986818595955647)]),
 RelationRecord(items=frozenset({'inception', 'Interstellar'}), support=0.015938923118135547, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar'}), items_add=frozenset({'inception'}), confidence=0.3216216216216216, lift=3.262536721504113)]),
 RelationRecord(items=frozenset({'The Wolf of Wall Street', 'inception'}), support=0.005357621216180016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Wolf of Wall Street'}), items_add=frozenset({'inception'}), confidence=0.3773584905660377, lift=3.8279327317473335)])]

**Proper Display**

In [11]:
def inspect(result):
    movie_1 = [tuple(result[2][0][0])[0] for result in result]
    movie_2 = [tuple(result[2][0][1])[0] for result in result]
    support = [result[1] for result in result]
    return list(zip(movie_1, movie_2, support))
result_in_dataframe = pd.DataFrame(inspect(result), columns=['Movie 1', 'Movie 2', 'Support'])

In [12]:
result_in_dataframe

                   Movie 1                   Movie 2   Support
0          Captain America             Black Panther  0.003349
1          Game of thrones  Comedy nights with Kapil  0.003215
2        Kanan Gill Comedy  Comedy nights with Kapil  0.008036
3          Game of thrones             Prision Break  0.004554
4           Harry Potter 1            Harry Potter 2  0.005759
5           Harry Potter 1     The Lord of the rings  0.005090
6    crimes of grindelwald            Harry Potter 2  0.005759
7             Interstellar                 inception  0.015939
8  The Wolf of Wall Street                 inception  0.005358

In [13]:
result_in_dataframe.nlargest(n=10, columns='Support')

                   Movie 1                   Movie 2   Support
7             Interstellar                 inception  0.015939
2        Kanan Gill Comedy  Comedy nights with Kapil  0.008036
6    crimes of grindelwald            Harry Potter 2  0.005759
4           Harry Potter 1            Harry Potter 2  0.005759
8  The Wolf of Wall Street                 inception  0.005358
5           Harry Potter 1     The Lord of the rings  0.005090
3          Game of thrones             Prision Break  0.004554
0          Captain America             Black Panther  0.003349
1          Game of thrones  Comedy nights with Kapil  0.003215